### ISSUE TITLE
Fatal error: undefined function is_plugin_active

### ISSUE THREAD

**Issue by joshlevinson** [NikV/WP-eCommerce-toolbar#1]
Hey, Nikhil! Sweet plugin here! I installed it this evening, but ran into a fatal error regarding the use of `is_plugin_active`.

The function `is_plugin_active` [isn't available until `admin_init` is fired](http://codex.wordpress.org/Function_Reference/is_plugin_active). There are a couple of workarounds:
- Load the plugin at a later hook (like `wp`)
- Include `wp-admin/includes/plugin.php` so you get to use `is_plugin_active` whenever you'd like.

Since the plugin is loaded primarily on the front end, the second option makes most sense, since you'll need to include that file to use `is_plugin_active` anywhere outside the admin anyway. A PR is on the way!

**Comment by NikV** [comment]
Merged!
